name: say test
on: [push, workflow_dispatch]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo 'test'
      - name: test
        env:
          TEST: aaaaaaaaaaa
          TEST_1: bbbbbbbbbbbbbb
        run: |
          env > .env
          cat .env

