name: Main workflow
on:
  repository_dispatch:
    types: [test]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: cp gs://${{ secrets.BUCKET_NAME }}/ssss/1.txt .
          cli: gsutil

